### ISSUE TITLE
Не отображаются иконки на кнопках

### ISSUE THREAD

**Issue by jdbit** [Ibochkarev/miniShop2#1]
![ 2013-02-24 16:24:38](https://f.cloud.github.com/assets/3685801/189514/0b4a5ce4-7e8e-11e2-9cf2-370070029981.png)

В админке не отображаются иконки. Путь к иконке img/mgr/glyphicons-halflings.png, но папки img в корне нет.

**Comment by Viktorminator** [comment]
img/mgr/ создайте папку и туда глификонки закачайте

**Comment by jdbit** [comment]
Я то в курсе как исправить, так и сделал. Просто сообщил об ошибке, чтобы в дальнейшем не париться  с заливкой иконок. Или такой баг проявляется только у меня? Хотя смотрел содержимое пакета, там вообще не видел файла с иконками...

**Comment by bezumkin** [comment]
<a href="https://github.com/bezumkin/miniShop2/tree/master/assets/components/minishop2/img/mgr">Файлики лежат на месте</a>, проблемы не вижу.

**Comment by jdbit** [comment]
Разобрался. Проблема была из-за включенного параметра compress_css. Из-за этого путь к файлу иконок был неправильным - http://site.com/img/mgr/glyphicons-halflings.png

**Comment by alroniks** [comment]
Вот PR #91, который решает эту проблему
