### ISSUE TITLE
Credit Amounts - request / enhancement

### ISSUE THREAD

**Issue by crimsonpixel** [Ibochkarev/miniShop2#100]
Hi there

Is it possible to issue a client with a credit in their account and as they order products this reduces until they get to a 0.00 balance when an alert to say "You've run out of credit please contact us to buy more credit" ?

**Comment by bezumkin** [comment]
I will try to add new default payment method that will work with **msCustomerProfile** object, that already has the column **account**.

Or you can write this payment method yourself.

**Comment by bezumkin** [comment]
See [msProfile](https://github.com/bezumkin/msProfile) package.
