### ISSUE TITLE
Скрипт импорта из CSV генерирует много логов

### ISSUE THREAD

**Issue by argnist** [Ibochkarev/miniShop2#103]
Столкнулся с тем, что после импорта товаров не смог войти в админку. Оказалось, что при входе админка падала на запросе:

```
SELECT COUNT( DISTINCT `modManagerLog`.`id` )
FROM `modx_manager_log` AS `modManagerLog`
JOIN `modx_users` `User` ON `modManagerLog`.`user` = `User`.`id`
WHERE (
`modManagerLog`.`occurred` > '2014-02-04, 12:19:08'
AND occurred = (
SELECT MAX( `occurred` )
FROM `modx_manager_log` AS log2
WHERE `log2`.`user` = `modManagerLog`.`user`
GROUP BY `user` )
)
```

А в свою очередь видимо этот запрос тупит, потому что при импорте в процессоре на добавление/удаление ресурсов генерируется много логов, минимум по 3 на ресурс: сам create/update ресурса, создание папки и создание файла-картинки. Сейчас такая проблема уже на 28029 записях в данной таблице. При очистке этой таблицы проблема с админкой пропадает.
То есть получается, что нецелесообразно использовать для импорта "базовые процессоры", это мало того, что медленно (1400 товаров обновляется около 10 минут), но и приводит к таким проблемам :(.

**Comment by bezumkin** [comment]
В чем вопрос-то? Не используй.

**Comment by argnist** [comment]
Это и не вопрос, это проблема). Проблема в том, что импорт не работает как полагается. Я попробую решить и пулл реквестнуть.

**Comment by bezumkin** [comment]
Импорт работает, как полагается.

Если в MODX пишется лог создаваемых объектов - это не проблема импорта. Если MODX падает при выборке большого количества записи из этой таблицы - это снова не проблема импорта.

Скрипт импорта создаёт товары через процессоры. Если есть желание, ты можешь создать 20000 товаров вручную и у тебя будет точно такая же проблема, без импорта.

Создание ресурсов без процессоров даже не предлагай - не приму. Лучше перепиши процессор выборки из лога действий MODX и предложи его авторам системы.

**Comment by argnist** [comment]
Ну можно даже так решить. Те логи, которые идут из импорта имеют **user** равным 0. Можно после завершения импорта просто их подчищать и проблемы не будет.

**Comment by bezumkin** [comment]
На bezumkin.ru сейчас 40,817 записей в modx_manager_log - ничего не падает.

Может еще и про хостинг стоит подумать?

**Comment by argnist** [comment]
Хостинг линод, точно такой же как у тебя, по твоим инструкциям настроенный. Проблема там не в количестве общем, а в количестве последних созданных записей.

**Comment by bezumkin** [comment]
Ну вот зайдет хозяин сайта в лог - там пусто, а на деле его мендежер в выходные обновил товары. И как он об этом узнает?

Напиши себе скрипт с TRUNCATE modx_manager_log и запускай его из консоли, если есть желание.

**Comment by argnist** [comment]
> Ну вот зайдет хозяин сайта в лог - там пусто, а на деле его мендежер в выходные обновил товары. И как он об этом узнает?

Можно добавить еще после этого **одну** запись в лог с ключом типа minishop2_import_success, что товары обновлены. И тогда поймет. В любом случае это будет лучше, чем если он совсем не сможет попасть в админку.

**Comment by bezumkin** [comment]
То есть, выходит, что проблемы с логами нет, с импортом нет, а есть только с запросом, который генерирует виджет админки?

Мне кажется, нужно его исправлять, а не удалять логи.

**Comment by bezumkin** [comment]
На всякий случай, еще раз повторюсь, что запись в лог генерирует modProcessor, это его базовая функция.

Все создаваемые и обновляемые объекты пишутся в лог. А ты предлагаешь не логировать или удалять информацию о том, что произошло на сайте. Я против.

**Comment by bezumkin** [comment]
С виждетами, кстати, вообще проблема, что они выполняются при загрузке админки, а не после.

Если у меня на локальной машине плохой интернет - я также не могу попасть в админку, потому что сайт грузит новости от modx.com.

**Comment by argnist** [comment]
Я понял твою позицию. Придется, как всегда, писать велосипеды, потому что импорт нужен уже сейчас, а исправление в ядре примут еще неизвестно когда, даже если его написать сейчас. В любом случае у меня вокруг csv.php своя обертка. Хотя бы, если у кого-то еще возникнет такая проблема, будет понятно куда копать.

Зы. Новости я отрубаю у всех сайтов сразу после их создания. Запускаю собственный скрипт, который переписывает настройки как мне надо, в том числе руссификацию всяких почтовых сообщений и т.п.

**Comment by bezumkin** [comment]
Так отключи виджет последних юзеров, раз такая проблема.

А я со своей стороны попробую его ускорить и предложить авторам MODX.

**Comment by bezumkin** [comment]
Ну что, переписал немного виджет, сможешь проверить у себя?

Вот код

<pre>
$c = $this->modx->newQuery('modManagerLog');
$c->innerJoin('modUser','User');
$c->where(array(
    'occurred:>' => strftime('%Y-%m-%d, %H:%M:%S',$timetocheck),
));
$c->select($this->modx->getSelectColumns('modManagerLog','modManagerLog', '', array('occurred'), true) . ', MAX(`modManagerLog`.`occurred`) as `occurred`');
$c->select($this->modx->getSelectColumns('modUser','User','',array('username')));
$c->groupby('user');
$c->sortby('occurred','DESC');
$ausers = $this->modx->getIterator('modManagerLog',$c);
</pre>

Нужно добавить его в <a href="https://github.com/modxcms/revolution/blob/develop/manager/controllers/default/dashboard/widget.grid-online.php">/manager/controllers/default/dashboard/widget.grid-online.php</a> и обновить товары на сайте. Потом зайти в админку и посмотреть на скорость загрузки виджета.

Если будет нормально работать, предложим в MODX.

---

У меня на тестовом сайте старый запрос выполняется 20 секунд, новый - 0.0160 (это я выбираю события за 2 дня). Результат, при этом, идентичен.

Так что, исправлять нужно виджет, а не логирование событий.

**Comment by argnist** [comment]
Ок,  сейчас проверю.

**Comment by argnist** [comment]
Ну вроде бы все нормально. При этом все равно таким способом созданные ресурсы, не попадают ни в журнал системы управления, ни в этот виджет, ни в виджет последних ресурсов. Просто засирают базу). Мне кажется дело в том, что user 0 получается.

**Comment by bezumkin** [comment]
Да, дело в юзере 0 - там в выборке INNER JOIN к юзерам.

Мне кажется, нужно поменять на LEFT JOIN, но в принципе, импорт может проводить и авторизованный юзер из браузера.

В любом случае, на скорость выборки это не влияет, и в текущей версии виджета выборка неправильная.

**Comment by bezumkin** [comment]
[Отправил коммит](https://github.com/modxcms/revolution/pull/11107), будем посмотреть.
