### ISSUE TITLE
небольшая добавочка к оформлению заказа

### ISSUE THREAD

**Issue by gaserge** [Ibochkarev/miniShop2#11]
незнаю нужно это или нет.
столкнулся с этим когда пробовал сделать свое оформление для магазина ( тоесть не bootstrap ), а например чекбоксы у меня через плагин оформляются ( и там доп. теги добавляются)

https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/web/default.js#L216
https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/web/default.js#L219

.parent(). заменить на .parents("label").

**Comment by bezumkin** [comment]
Это скрипт - просто пример.

Для своего сайта нужно просто копировать этот файл, менять, и указывать новый путь для подключения в системной настройке "ms2_frontend_js".
