### ISSUE TITLE
Feature request: add a system setting for chunk namespace

### ISSUE THREAD

**Issue by isaacniebeling** [Ibochkarev/miniShop2#114]
Since there are so many chunks involved in MiniShop, it'd be great to be able to put in a custom namespace to replace tpl.ms in chunk calls. That way, if you want to use customized chunks and ensure that they won't be reverted to defaults when updating, you just have to duplicate the defaults with your own namespace and change the system setting. Otherwise, you have to set a lot of template parameters within a lot of snippet calls.

**Comment by bezumkin** [comment]
Default chunks are not overwritten during update. You can select chunks to overwrite in setup options, but by default all checkboxes are inactive.

So, you can edit default chunks as you want without any troubles.

**Comment by isaacniebeling** [comment]
Great, thanks!
