### ISSUE TITLE
Translation on transifex

### ISSUE THREAD

**Issue by fourroses666** [Ibochkarev/miniShop2#115]
https://www.transifex.com/projects/p/revolution_core/language/pl/

**Comment by bezumkin** [comment]
Это что?

Я на польском не умею.

**Comment by fourroses666** [comment]
Transifex jest używany do tłumaczenia, więc jeśli uda Ci się umieścić go w Transifex wszystko można przetłumaczyć. Trochę trudno wyjaśnić, jak można to zrobić, bo sam nie wiem. Nie jestem programistą. : (

**Comment by fourroses666** [comment]
Można dodać tłumaczenie holenderskie? Nie jest całkowicie wykończone 60% są już wykonane.
http://goo.gl/UV7TdL
