### ISSUE TITLE
Привязка msOptions к фотографии товара

### ISSUE THREAD

**Issue by artbelov** [Ibochkarev/miniShop2#116]
Здравствуйте, Василий.

Часто бывает, что товару необходимо сделать привязку фото к определенному цвету.
И я хочу предложить решение, которое весьма простое и работает

_Данную функцию можно организовать чисто на JS и data-атрибутах HTML._

**Логика работы:**
_При смене "option":_ если описание фото и option совпадают, то переключить фото.
_При клике на фото:_ аналогичная операция, только с переключением "option".

**Пример реализации:**
http://mstylesamara.ru/bamper-cleave

**Вопрос:**
Cтоит ли делать pull-request с правками в "default.js" и чанках, или это не актуально, а решение не совсем изящное?

**Comment by bezumkin** [comment]
На мой взгляд нет, не стоит.

Для кастомизации очень много всего предусмотрено, так что не будем пихать всё в стандартный пакет.

**Comment by artbelov** [comment]
Вас понял. Учитывая, что часто иногда приходится делать "дополнения" к miniShop2 буду изредка спрашивать Вас об их надобности.
Спасибо.

_Скорее всего, просто сделаю заметку HOW-TO._

**Comment by bezumkin** [comment]
Да, how-to формат будет лучше. Спасибо!
