### ISSUE TITLE
Allow defining fields which should be formatted as Price or Weight in settings

### ISSUE THREAD

**Issue by rimas-kudelis** [Ibochkarev/miniShop2#117]
Currently, the list of fields that are being formatted as Price or Weight for display, are hardcoded in the msProducts snippet. Since ms2 plugins can add new fields to the schema, it would be great to be able to define the list of fields I want formatted that way, without editing the snippet itself.
# 

В настоящее время список полей, значения которых форматируются как цены или вес, прописан прямо в сниппете msProducts. По-скольку плагины ms2 могут добавлять свой поля, думаю было бы хорошо иметь возможность указать, которые поля нужно так форматировать, в настройках, дабы не надо было редактировать фабричный сниппет.

**Comment by bezumkin** [comment]
Создаём снипет **format_price**:

```
<?php
$ms2 = $modx->getService('miniShop2');
return $ms2->formatPrice($input);
```

И вызываем в чанке товара:

```
[[+any_number_field:format_price]]
```

**Comment by rimas-kudelis** [comment]
Спасибо за совет. Хм, а может тогда бы имело смысл и штатные поля таким-же образом выводить?
