### ISSUE TITLE
Сниппет msOrder выводит только 10 вариантов оплаты

### ISSUE THREAD

**Issue by vbatushev** [Ibochkarev/miniShop2#132]
Собственно, там просто нет указания limit при выборке и pdoFetch берет 10 payment по умолчанию.

**Comment by bezumkin** [comment]
Попробуй указать в вызове сниппета

```
&limit=`50`
```

Судя по коду, должно работать.

**Comment by vbatushev** [comment]
Ах, ты ж. Об этой возможности не подумал, правил все время. Спасибо!

**Comment by rozasmerti** [comment]
вот кстати вчера буквально обновляла mninshop до последней версии и опять столкнулась с проблемой limit=10, только в моем случае на варианты доставки. Думаю такое часто бывает при наличии пунктов самовывоза с кучей адресов в каждом городе.
До обновления пришлось править это дело в сниппете msOrder и конечно оно слетело после перехода на свежую версию.  Клиенты были расстроены сим фактом.
Кстати вызов параметра не работает, снипет вообще не срабатывает с этим параметром. Хотя почему это на моей системы проявилось именно что отключением сниппета при вызове параметра я затрудняюсь так сходу сказать, судя по коду сниппета все хорошо же должно быть, на первый взгляд. Дебаг включать лень, но не исключаю что дело именно в особенностях моей системы, а не в сниппете - хотя на банальные опечатки несколько раз вызов проверила.
 Да и не ясно к чему этот limit будет относиться к вариантам доставки или к вариантам оплаты. Предусмотрите, пожалуйста, этот момент, в будущих версиях. То есть по идее нужны два параметра limit-а для доставки и оплаты, либо в целом ограничение отключить.
Доп: с параметром все ясно, все же опечатка с моей стороны) И все равно нужны 2 разных limit-а по логике.
