### ISSUE TITLE
Unknown error - message

### ISSUE THREAD

**Issue by veqlargh** [Ibochkarev/miniShop2#14]
When i add to basket a popup notification in top right apers in red with message "Unknown error". In error log there is no entry. Do you have any idea?
Thanks!

**Comment by bezumkin** [comment]
It is happends if you send wrong action to connector. Look at browser console, what action you send on click?
It must be "cart/add".

Also, if you have enabled php-apc, please, disable it.

<a rel="fancybox" href="http://st.bezumkin.ru/files/2/a/8/d/a8dfd23e8620956860c23fcc925f0c58.png"><img src="http://st.bezumkin.ru/files/2/a/8/d/a8dfd23e8620956860c23fcc925f0c58_thumb.png" width="300" class="fancybox thumbnail center"></a>

**Comment by veqlargh** [comment]
hi,
on click there is card/add. 
You can see the page here http://pirueta-shop.com/index.php?id=36
![error](https://f.cloud.github.com/assets/3168759/273051/41b03df0-9016-11e2-92e7-86a978038198.jpg)

**Comment by bezumkin** [comment]
Can you send to bezumkin@yandex.ru credentials for admin access?

**Comment by bezumkin** [comment]
Disable <b>register_globals</b> in you php.

**Comment by veqlargh** [comment]
I can only use .htaccess to disable it.. so i did that.. php_flag
register_globals Off

Still nothing..

2013/3/19 Bezumkin notifications@github.com

> Desable _register_globals_ in you php.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bezumkin/miniShop2/issues/14#issuecomment-15103663
> .

## 

.

**Comment by bezumkin** [comment]
Because of your hosting provider. Look in phpinfo() - register_globals are still enabled.
<a rel="fancybox" href="http://st.bezumkin.ru/files/2/f/2/a/f2a3b4eba392a6db7c95b22d96f74dd2.png"><img src="http://st.bezumkin.ru/files/2/f/2/a/f2a3b4eba392a6db7c95b22d96f74dd2_thumb.png" width="300" class="fancybox thumbnail center"></a>

**Comment by veqlargh** [comment]
I checked at my hosting provider and I can't change register_globals. Is
there anything else that we can do?

2013/3/19 Bezumkin notifications@github.com

> Because of your hosting provider. Look in phpinfo() - register_globals are
> still enabled.
> http://st.bezumkin.ru/files/2/f/2/a/f2a3b4eba392a6db7c95b22d96f74dd2.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bezumkin/miniShop2/issues/14#issuecomment-15104358
> .

## 

.

**Comment by bezumkin** [comment]
Yes, you need to change this provaider, really. Google about register_globals, it very dangerous option.

But, of course, you also can change 
<code>switch ($action)  {</code>
to 
<code>switch ($_REQUEST['action']) {</code>
in <b>/assets/components/minishop2/action.php</b>

And there is no guarantee that will no another errors.

**Comment by veqlargh** [comment]
Ok. Now I don't get an error.
But I get only one item in cart, and when I add another one cart doesen't
refresh. And my cart resource is empty..

_Is this because of register_globals?

2013/3/20 Bezumkin notifications@github.com

> Yes, you need to change this provaider, really. Google about
> register_globals, it very dangerous option.
> 
> But, of course, you also can change
> switch ($action) {
> to
> switch ($_REQUEST['action']) {
> in _/assets/components/minishop2/action.php_
> 
> And there is no guarantee that will no another errors.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bezumkin/miniShop2/issues/14#issuecomment-15170957
> .

## 

.

**Comment by bezumkin** [comment]
Maybe.

Anyway, your server is misconfigured and I can not help you anymore.
