### ISSUE TITLE
Сниппет mFilter не правильно обрабатывает значения полей с запятой

### ISSUE THREAD

**Issue by alexroot** [Ibochkarev/miniShop2#142]
Если поле содержит знак запятой, то фильтр значения фильтра поле выводится серым или при фильтрации (установке галки) -> "поиск не дал результатов"

**Comment by bezumkin** [comment]
В настройках сниппета есть возможность задать другой разделитель для значений.

http://docs.modx.pro/components/msearch2/snippets/mfilter2 - параметр &values_delimeter.
