### ISSUE TITLE
Генерация миниатюр

### ISSUE THREAD

**Issue by Bournwog** [Ibochkarev/miniShop2#146]
Хотелось бы видеть в админке управление генерацией миниатюр:
1)Удалить все миниатюры
2)Сгенерировать миниатюры к товарам с указанием количество генерируемых за раз и интервалом обновления 
3)Перегенерация миниатюр - объединяет первый и второй шаги
4)Генерация/перегенерация миниатюр налету из сниппета(2 параметра нужна генерация, и форсировать генерацию для текущих изображений)

Для чего это все надо - например создали магазин и все работает занесли 1к товара, потом заказчик хочет изменить размер изображения у товаров, и все надо либо писать свою обработку подсмотренную modx.pro которая работает к тому же криво на 15к+ товаров либо искать другой способ, так же актуально если изображения загружаются из 1С и новым необходимо выполнять генерацию миниатюр, как вариант параметр к сниппету, не сильно увеличит нагрузку на SQL и при первой генерации будет подгружаться подольше но за то, при следующей загрузке все отработает из уже сгенерированного содержимого

**Comment by bezumkin** [comment]
1) Зачем? Миниатюры можно сгенерировать заново, старые при этом удаляются. Картинок без миниатюр быть не должно - такова логика работы галереи товара.
2) См. пункт 1.
3) См. пункт 1.
4) https://bezumkin.ru/modx/minishop2/solutions/1465/ - нужно совсем чуть-чуть изменить для одного товара, а не всех сразу.

**Comment by Bournwog** [comment]
Решение из коробки всегда полезно, я привел примеры для которых оно может пригодиться, добавив всего 2 параметра к сниппету msProducts и два к msGallery мы получаем удобный инструмент для обновления миниатюр при перестроении сайта, а добавив в админ панель возможность перегенерации всех миниатюр мы не будем модифицировать разные участки кода для выполнения конкретной задачи. 

При этом совершенно не значит что я не могу написать все это, просто другим кто не может явно будет полезно решение из коробки.

P.S. А скрипт по ссылке я в свое время пробовал - он умирает на некоторых изображениях, правда не было желания разбираться почему, поэтому написал свое решение. 

P.P.S. И кстати перегенерация миниатюр из больших фотографий тоже проблемна, если фотографии занимают по 7-10 мегабайт, то генерация миниатюр хотя бы для 5 фотографий подвесит скрипт на достаточно длительное время, может не хватить и 30-60 секунд выполнения скрипта, и получить недогенерированные изображения с ошибками

**Comment by bezumkin** [comment]
> если фотографии занимают по 7-10 мегабайт, то генерация миниатюр хотя бы для 5 фотографий подвесит скрипт на достаточно длительное время, может не хватить и 30-60 секунд выполнения скрипта, и получить недогенерированные изображения с ошибками

Не может быть! А должно то ведь выполняться за милисекунду на любом объеме, ну как же так?

Про всё остальное - присылай готовые коммиты, я добавлю. В одиночку делать магазин мечты сил давно нет.

**Comment by Bournwog** [comment]
Понимаю, постараюсь присылать, надеюсь на помощь в реорганизации кода
