### ISSUE TITLE
[2.1.8-rc2] Duplicate Product processor not  found in MODx 2.3.1

### ISSUE THREAD

**Issue by lithiumlab** [Ibochkarev/miniShop2#148]
This error comes out when trying to duplicate a product via the Copy Button inside the product in Modx 2.3.1:

```
 [2014-08-06 11:19:03] (ERROR @ /connectors/resource/index.php) Processor /core/model/modx/processors/duplicate.php does not exist; Array
(
    [action] => duplicate
)

```

This button:

![screen shot 2014-08-06 at 12 25 50 pm](https://cloud.githubusercontent.com/assets/494499/3830050/67baaab8-1d86-11e4-8dd5-684aabbd5872.png)

**Comment by lithiumlab** [comment]
Great!
btw amazing extra.
Solid interface and gallery manager for the use case.
It looks and works really good in 2.3.1.

**Comment by bezumkin** [comment]
Thanks!
