### ISSUE TITLE
Can't update 2.1.7 ?

### ISSUE THREAD

**Issue by fourroses666** [Ibochkarev/miniShop2#149]
MODX Revolution 2.2.13-pl (traditional)

See:
![error](https://cloud.githubusercontent.com/assets/523389/3858456/0253615e-1f0e-11e4-9f66-5f57ccbd2264.png)

Manual update?

**Comment by bezumkin** [comment]
<img src="https://file.modx.pro/files/3/f/f/3ffcd4baeed89c94966ff42c10df4f44.png" />

**Comment by fourroses666** [comment]
you are right, thats what I tried next. (I'm still a rookie at Revo) but now I see:

![hmmz](https://cloud.githubusercontent.com/assets/523389/3858717/b44eecfa-1f10-11e4-9f3f-af678487ba9a.png)

some server setting not correct?

![yo](https://cloud.githubusercontent.com/assets/523389/3858751/144d7d7e-1f11-11e4-82d6-4aedd98eea9d.png)

**Comment by fourroses666** [comment]
second attempt worked hmmzz dunnooo
