### ISSUE TITLE
[2.1.8-rc2] Minishop csv import process is not checking source in the csv file.

### ISSUE THREAD

**Issue by lithiumlab** [Ibochkarev/miniShop2#151]
Hi;
I've made a few successful imports through the console using the csv.php supplied in the package and using this link translated to english using Google Translate to follow instructions...

http://translate.google.com.do/translate?hl=en&sl=ru&u=https://bezumkin.ru/modx/minishop2/import/2309/&prev=/search%3Fq%3Dminishop2%2Bimport%2Bcsv.php%26espv%3D2%26biw%3D1780%26bih%3D1170

But,
If you specify a "source" field in the .csv images and upload the images-to-be-imported to that folder the import process will search for that images taking the "source" in consideration. This is not happening. The import process is looking for the images still in the root folder even if "source" field is specified in the csv and row has the id value (in my case "3") of the source.

Here's my call through ssh:

```
php ./core/components/minishop2/import/csv.php "import.csv" "article, pagetitle, vendor, parent, gallery, source" 0 "article" 1 ","
```

Which throws up this error:

```
[2014-08-11 06:39:27] (INFO @ ./core/components/minishop2/import/csv.php) Successful create: 
Array
(
    [id] => 226
)

[2014-08-11 06:39:27] (INFO @ ./core/components/minishop2/import/csv.php) Importing images: 
Array
(
    [0] => Brooklyn 130_70_dét.jpg
)

[2014-08-11 06:39:27] (ERROR @ ./core/components/minishop2/import/csv.php) Could not import image "Brooklyn 130_70_dét.jpg" to gallery. File "/paas/cXXXX/www/Brooklyn 130_70_dét.jpg" not found on server.
```

Here's a row of the csv file:

```
128,Brooklyn 130 70 dét ,6,224,Brooklyn 130_70_dét.jpg,3

```

I'm using MODx 2.3.1 in a modxcloud for the test.
Hope my efforts are not getting lost in translation :)

**Comment by bezumkin** [comment]
The import process is looking for the images in the root folder for **upload** them to specified source.

You can upload them from any folder in the site:

```
/assets/images/Brooklyn 130_70_dét.jpg
```

**Comment by lithiumlab** [comment]
Aaaah!
Thanks for clarification.
Its a really useful process.
I'm using it to get around 2,000 items and it works great.

**Comment by bezumkin** [comment]
You are welcome!
