### ISSUE TITLE
[[+vendor]] выводит не название а Id прозводителя - так и было задумано?

### ISSUE THREAD

**Issue by asxasx** [Ibochkarev/miniShop2#16]
Если да, то может есть простой способ его имя вывести? Не очень простой я примерно представляю, но мали может просто можно.

**Comment by bezumkin** [comment]
Да, конечно, vendor в поле товара и есть id производителя.

На странице товара и в каталоге (сниппет msProducts) данные производителя выводятся через префикс <b>vendor.</b>

То есть: [[+vendor.name]], [[+vendor.logo]] и т.д.

**Comment by asxasx** [comment]
Ну я и тормоз! Спасибо за развернутый ответ!
