### ISSUE TITLE
Сепаратор для msOption

### ISSUE THREAD

**Issue by asxasx** [Ibochkarev/miniShop2#19]
Было бы логично добавить в параметры возможность указать сепаратор для вывода опций. Не всегда опции нужны листбоксом, иногда нужно просто перечислить. Если в чанк сепаратор добавить, то он будет выводится даже если элемент всего 1.

**Comment by bezumkin** [comment]
Теперь можно указывать в чанке <b>tpl.msProducts.row</b> вот так:

``` php
[[!msOptions?product=`[[+id]]`&name=`tags`&tplRow=``&tplOuter=``&outputSeparator=`; `]]
```
