### ISSUE TITLE
Сокращается дробная часть в стоимости продукта

### ISSUE THREAD

**Issue by jdbit** [Ibochkarev/miniShop2#3]
При указании цены, например, $11,50, в итоге получаем сокращенный вариант $11,5.

**Comment by bezumkin** [comment]
Так работает xPDO - он убирает лишние нули.

Также делает и мой сниппет, чтобы всё выглядело одинаково. У него <a href="https://github.com/bezumkin/miniShop2/blob/634a99f50246de476940069a8c244ed5c5f91afe/core/components/minishop2/elements/snippets/snippet.ms_products.php#L144">это можно закомментировать</a>, а вот с xPDO ничего не поделать.
