### ISSUE TITLE
Only User 1 can save and create categories

### ISSUE THREAD

**Issue by wshawn** [Ibochkarev/miniShop2#30]
The save button is missing on other administrative level 0 users.  Please correct this.

From the Access Control Policy:

miniShopManagerPolicy

A policy for create and update miniShop categories and products.

miniShopManagerPolicyTemplate

5 of 2

Why is it 5 of 2?

**Comment by bezumkin** [comment]
Creating categories requires _mscategory_save_ permission.

Try to apply miniShopManagerPolicy to Administrator group or enable sudo.
