### ISSUE TITLE
Поле "Размер" - понимает только цифры

### ISSUE THREAD

**Issue by asxasx** [Ibochkarev/miniShop2#4]
Поле где вводим размер похоже  понимает только цифры. Было бы отлично добавить поддержку размеров вида XS/S/M/L/XL итд.

**Comment by bezumkin** [comment]
Нет, там понимается всё что угодно.

<a rel="fancybox" href="http://st.bezumkin.ru/files/2/5/7/6/576a5e2fe25b3c6c464624b401f0193f.png"><img src="http://st.bezumkin.ru/files/2/5/7/6/576a5e2fe25b3c6c464624b401f0193f_thumb.png" width="300" class="fancybox thumbnail center"></a>
