### ISSUE TITLE
minishop2 snippet msGetOrder options column

### ISSUE THREAD

**Issue by nnmer** [Ibochkarev/miniShop2#43]
Василий,

Возникла проблемка с сниппетом. Не вытаскивает из базы опции товара в заказе.

Добавил для теста в код сниппета вывод в лог:
<code>  // Additional properties of product
    $modx->log(modX::LOG_LEVEL_ERROR,$row['options']);
    $options = json_decode($row['options'],1);
    $modx->log(modX::LOG_LEVEL_ERROR,print_r($row['options'],true));</code>

в логах тишина

**Comment by nnmer** [comment]
версия minishop2 - 2.0.1 beta1

**Comment by bezumkin** [comment]
http://bezumkin.ru/sections/help/1287/

**Comment by nnmer** [comment]
я всё понимаю, конечно же используется правильный чанк. Я про сниппет. если в самом сниппете делаю вывод в лог опций товара - вывод пустой!

**Comment by bezumkin** [comment]
Ты в БД посмотри, может у тебя и в правду опций нет?

**Comment by nnmer** [comment]
в таблице ms2_order_product в колонке options есть данные - json строка с параметрами, в моем случае с параметрами цвета и ширины

**Comment by bezumkin** [comment]
Добавляю на 102 строку сниппет

<pre>print_r($rows);die;</pre>

открываю консоль, переключаю на последний ответ от сервера и вижу, что в options данные есть.
<a rel="fancybox" href="http://st.bezumkin.ru/files/f/0/0/f00b5ecb54e159061ad0eb9d9be13945.png"><img src="http://st.bezumkin.ru/files/f/0/0/f00b5ecb54e159061ad0eb9d9be13945s.jpg" class="fancybox thumbnail center"></a>
Так что, сниппет получает и выводит в плейсхолдеры опции. Почему у тебя в логе не появляется - не знаю.
