### ISSUE TITLE
Please add a prefix to your build so as not to confuse miniShop tables with MODX

### ISSUE THREAD

**Issue by wshawn** [Ibochkarev/miniShop2#48]
Third-party Packages should not be using the same prefix as MODX itself. You can probably use ms2 as your prefix.

Please change this.

**Comment by bezumkin** [comment]
Where did you see tables without prefix in my <a href="https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/schema/minishop2.mysql.schema.xml">schema</a>?
