### ISSUE TITLE
Не сохраняются TV

### ISSUE THREAD

**Issue by pulsar88** [Ibochkarev/miniShop2#5]
У категорий и товаров не сохраняются параметры шаблона (TV). У обычных документов все нормально.

**Comment by pulsar88** [comment]
![ms2](https://f.cloud.github.com/assets/3817489/239756/96b75d74-88c8-11e2-8dd2-444cd88771e6.png)
Хм..странная штука получилась. TV не сохраняются только в одной категории, на картинке обозначена стрелкой. При этом внутри нее есть несколько товаров, но они не выводятся в дереве документов, что на картинке. Вложенные товары редактируются, во фронт-енде выводятся, но у них не сохраняются TV, при этом саму категорию удалить невозможно, выдает ошибку. В остальных категориях все нормально: TV сохраняются, в дереве вложенные продукты отображаются, удалить можно.

**Comment by pulsar88** [comment]
Василий!
Все-таки непонятка с TV дает о себе знать. Время от времени (не знаю по какой логике и с чем связано) создаваемый товар становится каким-то "кривым", т.е. внешне все нормально, но при его изменении не сохраняются TV и MODX в логах выдает:
[2013-03-11 22:30:01](ERROR @ /connectors/resource/index.php) Error HY000 executing statement: 
Array
(
    [0] => HY000
    [1] => 2014
    [2] => Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
)
Есть предположения с чем это связано?

**Comment by bezumkin** [comment]
Бегло погуглив, выясняется, что это проблема работы с PDO. Непонятно, где именно и когда она возникает, но в работу с ТВ я не смешивался - там всё родное.

Если вычислишь закономерность - смогу исправить, так как я не видел таких ошибок в MODX пока ни разу.

**Comment by pulsar88** [comment]
Василий, обнаружил закономерность.

Если забить любое из полей - Цвета, Размеры, Теги, затем сохранить товар, и после этого изменить ТВ - изменения не сохраняются и в логах МОДХа вываливается ошибка. Видимо работа с этими полями мешает МОДХу в работе с ТВ. В коде еще не ковырялся - найду, сообщу.

**Comment by bezumkin** [comment]
Попробуй внести <a href="https://github.com/bezumkin/miniShop2/commit/774315f0e5bcdeba2c1d10853019900fd98ae40c">вот эти изменения</a>, вдруг поможет? Тут я резко сократил кол-во PDO запросов при сохранении опций товара.

Теперь на 1 поле - один запрос.

**Comment by asxasx** [comment]
Точно такая же проблема, внесение изменений не помогает.

**Comment by bezumkin** [comment]
Можешь прислать доступ в админку на bezumkin@yandex.ru?

**Comment by asxasx** [comment]
Ок, завтра пришлю.

**Comment by bezumkin** [comment]
Эта ошибка возникает только на хостах с версией php 5.2. Есть она и на <a href="https://bugs.php.net/bug.php?id=44081">трекере</a>.

В php 5.2 очень плохо организована работа с хранимыми процедурами, что приводит к ошибке при попытке сохранить опции товара в таблицу msProductOption, во время сохранения самого товара.

В код MODX я залезть не могу, код miniShop2 для поддержки старого php менять не хочу. Так что выхода ровно два:
- перейти на php 5.3, предпочтительный
- Заменить вот <a href="https://github.com/bezumkin/miniShop2/blob/8bba551056740a2f4b0247c0cbf3e611a27aa765/core/components/minishop2/model/minishop2/msproductdata.class.php#L14">эту строку</a> на:
  <code>
  return parent::save();
  </code>
  Тогда у вас не будет работать сниппет msOptions и вы не сможете искать товары по опциям через xPDO.
