### ISSUE TITLE
Проверка Tickets

### ISSUE THREAD

**Issue by bezumkin** [Ibochkarev/miniShop2#50]
Изменить проверку наличия компонента Tickets.

Можно просто проверять объявление класса Ticket.

**Comment by vitvayti** [comment]
Установил miniShop2 и загрузил Tickets (не устанавливал) - перестали открываться категории товаров на редактирование, в этой теме именно об этом идет речь?

**Comment by bezumkin** [comment]
Да. Или установи, или удали.
