### ISSUE TITLE
Оформление заказа после авторизации hybridauth

### ISSUE THREAD

**Issue by denysbutenko** [Ibochkarev/miniShop2#6]
Если авторизоваться через HybridAuth (Twitter), добавить товаров в корзину, и нажать оформить заказ, то ничего не произойдет. А в консоле появится ошибка 
Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://domain/assets/components/minishop2/action.php
Если выйти из аккаунта и ввести такие же данные в заказ - все норм.
Проверил дважды и на чистой установке тоже.

**Comment by bezumkin** [comment]
А что в логах сервера то?

**Comment by denysbutenko** [comment]
nginx:
2013/03/10 15:43:14 [error] 13892#0: *11748 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use object of type msOrderHandler as array in /var/www/hlapo/www/core/components/minishop2/model/minishop2/minishop2.class.php on$

**Comment by bezumkin** [comment]
На какой строке? 
...op2.class.php on$ - тут должен быть номер строки.

Ошибка только после авторизации через HA, или на всех заказах?

**Comment by denysbutenko** [comment]
Да, действительно, строка не полностью скопировалась, на 162 строке. Да, только после авторизации, если выйти - все нормально.

**Comment by bezumkin** [comment]
Ага, <a href="https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/minishop2/minishop2.class.php#L162">косяк</a>.

Спасибо, пофикшу.
