### ISSUE TITLE
Имена файлов в гелерее

### ISSUE THREAD

**Issue by bezumkin** [Ibochkarev/miniShop2#63]
Подумать о возможности генерации имени загруженного файла в зависимости от загружаемого.

Возможно, стоит прикрутить translit для этого.

**Comment by AlexeyAndKartashov** [comment]
Поковыряй ptoaric - https://github.com/antixrist/ptoaric
Очень, очень гибкий в этом плане. Ему можно скармливать любые пути: './images/pic.jpg', 'images/pic.jpg', 'images/pic.jpg', '/root/path/domain.com/images/pic.jpg' - всё корректно сожрёт и обработает в соответствии с настройками.
Разрешаю его использовать как угодно. По-моему это называется MIT-license, если я правильно помню)

**Comment by bezumkin** [comment]
Спасибо!

Только тут не нужно пути парсить, а нужно взять имя файла, поменять русские буквы на английские, вырезать левые символы, пробелы и т.п.
Чтобы загружаемый файл "белое пальто!.JPG" превратился на сервере в "beloe_palto.jpg".

Работу по сохранению файлов и выдаче берет на себя источник файлов, тут ничего менять не нужно.
