### ISSUE TITLE
Нельзя отключить автоматическую подгрузку дефолтных скриптов и стилей и засунуть из в Minifix.

### ISSUE THREAD

**Issue by AndrewDro** [Ibochkarev/miniShop2#632]
## Сообщение об ошибке / Error message

в head перестаёт инициализироваться переменная miniShop2Config при удалении из настроек дефолтных скриптов и стилей (ms2_frontend_js и ms2_frontend_css), выдаёт ошибку - "miniShop2 is not defined"

### Резюме / Summary

При добавлении скриптов и стилей минишопа в сниппет Minifix-a столкнулся с такой проблемой, после удаления скриптов и стилей фронтенда из настроек минишопа (ms2_frontend_js и ms2_frontend_css), чтобы они не грузились два раза, перестаёт инициализироваться переменная miniShop2Config в head, хотя все скрипты и стили минишопа добавляются в минимизированный файл (проверил), причем в том порядке, в котором они работали до добавления в группы и прехуки Minifix-a.
Из-за этого перестаёт нормально работать сайт.

### Шаг для воспроизведения / Step to play

проблема описана ещё здесь:
[https://modx.pro/components/14353#comment-130662](url)

**Comment by AndrewDro** [comment]
Вопрос забыл)
Нельзя ли как-то подкрутить минишоп чтобы он работал с пустыми настройками ms2_frontend_js и ms2_frontend_css?
Смотрю что tickets и optionprice2 инициируют свои переменные в head с пустыми аналогичными настройками, а минишоп нет.

**Comment by biz87** [comment]
> Вопрос забыл) Нельзя ли как-то подкрутить минишоп чтобы он работал с пустыми настройками ms2_frontend_js и ms2_frontend_css? Смотрю что tickets и optionprice2 инициируют свои переменные в head с пустыми аналогичными настройками, а минишоп нет.

В минишопе с самого начала и по сей день была такая возможность. 
У меня вообще на всех проектах дефолтные настройки выключены, а код минишопа через сборщик скриптов подключается.

**Comment by biz87** [comment]
Я пропустил, что вопрос конкретно про **miniShop2Config**  - да судя по всему если не добавлять эти данные в код JS приложения - будут проблемы.  Нужно подумать - проблема ли это вообще, глобальная ли она, и есть ли смысл ее решать. 
У нас в любом случае планируется перестройка всего JS

**Comment by AndrewDro** [comment]
> У меня вообще на всех проектах дефолтные настройки выключены, а код минишопа через сборщик скриптов подключается.

странно, а как у Вас тогда появляется **miniShop2Config** в head? у меня он пропадает в случае отключения ms2_frontend_js и ms2_frontend_css и сайт перестаёт нормально работать.. неужели у меня особый случай)

**Comment by AndrewDro** [comment]
> Нужно подумать - проблема ли это вообще, глобальная ли она, и есть ли смысл ее решать.

ну не знаю, если сайт перестаёт работать нормально, как считаете, проблема это и насколько она глобальна по пятибальной шкале?)

**Comment by AndrewDro** [comment]
в общем закостылил такой вариант)
добавил в файл minishop2.class.php на строку 143 такой код:
```
if (empty($js)) {
                $message_setting = array(
                    'close_all_message' => $this->modx->lexicon('ms2_message_close_all'),
                );

                $js_setting = array(
                    'cssUrl' => $this->config['cssUrl'] . 'web/',
                    'jsUrl' => $this->config['jsUrl'] . 'web/',
                    'actionUrl' => $this->config['actionUrl'],
                    'ctx' => $ctx,
                    'price_format' => json_decode(
                        $this->modx->getOption('ms2_price_format', null, '[2, ".", " "]'),
                        true
                    ),
                    'price_format_no_zeros' => (bool)$this->modx->getOption('ms2_price_format_no_zeros', null, true),
                    'weight_format' => json_decode(
                        $this->modx->getOption('ms2_weight_format', null, '[3, ".", " "]'),
                        true
                    ),
                    'weight_format_no_zeros' => (bool)$this->modx->getOption('ms2_weight_format_no_zeros', null, true),
                );

                $data = json_encode(array_merge($message_setting, $js_setting), true);
                $this->modx->regClientStartupScript(
                    '<script>miniShop2Config = ' . $data . ';</script>',
                    true
                );
            }
```
вроде работает и теперь можно подключаемые на страницу файлы минишопа засунуть в один файл minifix-а, а дефолтное подключение отключить, и все функции на сайте работают нормально…

**Comment by Alexij2** [comment]
Проблема актуальна. и править исходники как-то не комильфо.
нужно как-то разделить конфиг и js скрипт. Можно конечно скопировать данные кофнига и подрубать самому так, но на сколько это будет оправданно в ручном режиме? Ведь туда попадают различные настройки.

**Comment by EMDM45** [comment]
Вообще в MinifyX есть плагин, который сжимает скрипты, подключаемые через API.
Т.е. достаточно просто поставить галочку в настройках MinifyX, без стирания "дефолтных" сриптов miniShop2. И должно работать.
