### ISSUE TITLE
Optional elements?

### ISSUE THREAD

**Issue by exside** [Ibochkarev/miniShop2#7]
Hi,

first of all thanks for your hard work on this nice extra, though I have a little difficulties to wrap my head around it (obviously I don't speak russian =D)!

I noticed that a lot of elements get created when installing minishop2 and I just wanted to ask if it is somehow possible to make them optional (though they are probably in core folder anyways, as static files, so if I want them I could add them later manually)?

**Comment by bezumkin** [comment]
No. You feel sorry for a few kilobytes?

It is default functionality of component. Otherwise I'll be swamped with questions "and how does it work?"

**Comment by exside** [comment]
Nope, it's not about the kilobytes =), more about having control over what elements are created in my db.

and yes sure, the standard elements should be activated/checked by default, but it would be nice to have the option to install them or not...
