### ISSUE TITLE
Исчезновение категорий товаров из дерева во вкладке "Свойства товара".

### ISSUE THREAD

**Issue by akimsullec** [Ibochkarev/miniShop2#78]
Привет!
Василий, я заметил вот такую странность.
Сначала о своей реализации.
У меня есть товары двух типов. Для каждого типа товара есть главная категория внутри которой есть несколько подкатегорий.
Каждый товар может быть в какой либо категории или подкатегории, назначаемой главной для него в момент создания товара. А также товар может быть включен в несколько дополнительных категорий.

Теперь поведение.
До первого сохранения нового документа принадлежность к какой-либо категории или подкатегории можно выбрать в разделе «Веб страница». Это нормально :)
Теперь внимание.
Если товару при создании назначена подкатегория (вложенная в одну из двух основных категорий), то если её изменить (в разделе «Веб страница») — предыдущая категория исчезнет из дерева категорий (которое во вкладке «Свойства товара»).
Таким образом можно спрятать Н-ное количество подкатегорий. С главными категориями так не получается. Всё окей.

www.youtube.com/watch?v=mTTaUmQjtFQ

Пока писал, нашел как пофиксить :)
Оказалось, что подкатегория пропала для всех товаров.
Потом оказалось что также может пропасть и категория.

Чтобы пофиксить надо зайти в подкатегорию и сохранить ее заново. Например, поставить в имени пробел и удалить его, потом нажать «Сохранить».

В журнале [2013-09-30 22:37:30](ERROR @ /assets/components/minishop2/connector.php) No class specified for loadClass

А! Самое главное!
Это началось давно. То есть не с последнего релиза.

И еще. После исчезновения из дерева во вкладке "Свойства товара", категории остаются в дереве ресурсов и в выпадающем списке категорий разделе "Веб страница".

**Comment by bezumkin** [comment]
Есть ли баг на последних версиях MS2?

Я не могу повторить.

**Comment by akimsullec** [comment]
MODX Revolution 2.2.11-pl
minishop2-2.1.5-pl

Баг есть.
Манипуляции проводил в хроме, после чего удалил кэш (вручную, а не через CMS) и запустил IE. Там статус дерева такой же - нет подкатегорий. То есть проблема не в браузере или  кэше получается.

**Comment by bezumkin** [comment]
Сможешь показать на http://test.modx.pro?

**Comment by bezumkin** [comment]
Прикольный баг.

Фокус в том, что если переносишь **последний** товар из категории, то стандартный процессор MODX ставит этой категории isfolder = false и она не выбирается в списке.

А при сохранении процессором MS2 isfolder снова становится true и всё ок.
