### ISSUE TITLE
Удаление заказов

### ISSUE THREAD

**Issue by gaserge** [Ibochkarev/miniShop2#8]
некорректно удяляются заказы, если их много и удалять правой кнопкой мыши.
фикс в файле: miniShop2 / assets / components / minishop2 / js / mgr / orders / orders.grid.js
,removeOrder: function(btn,e) {
        if (!this.menu.record) return false;

```
    MODx.msg.confirm({
        title: _('ms2_menu_remove') + ' ' + _('ms2_order') + ' #' + this.menu.record.num
        ,text: _('ms2_menu_remove_confirm')
        ,url: miniShop2.config.connector_url
        ,params: {
            action: 'mgr/orders/remove'
            ,id: id
```

последняя строка ,id: id, заменить на this.menu.record.id

**Comment by bezumkin** [comment]
Спасибо ,поправлю.

Для массового удаления можно выделить заказы чекбоксом слева, и удалить несколько за раз.
