### ISSUE TITLE
Сомнения в поддержке мультисайтовости.

### ISSUE THREAD

**Issue by akimsullec** [Ibochkarev/miniShop2#80]
Прицепил к ядру с установленным MS2 второй сайт.
Установил на новом сайте MS2 и все кастомные файлы MS2,  находящиеся внутри core были затерты при установке.

Все что было кастомного  в assets и БД старого сайта - осталось, т.к. у нового сайта фронтенд находится в другом каталоге и БД своя.

MODX Revolution 2.2.9-pl (advanced)
MS2: 2.1.0-pl2

**Comment by bezumkin** [comment]
Взял и перезаписал директорию - компонент здесь при чем?

**Comment by akimsullec** [comment]
Вась, дело в том, что если бы я изменял файлы из пакета - вопросов нет. Они конечно же перезаписываются. Но я говорю о том, что затерты были мои файлы с уникальными именами (таких в установочном пакете нет).  То есть эти файлы в папках были, а после переустановки их нет.

**Comment by bezumkin** [comment]
Это потому, что второй сайт устанавливал пакет заново, и просто затер директорию целиком. Он же не знает про другую установку.
Если бы это был не отдельный сайт, а второй контекст - вопроса бы не было.

Думаю, что можно сейчас вернуть эти файлы на место и потом обновлять пакет с 2х сайтов - затераний быть не должно. ну а если нет бэкапов - могу только посочувствовать.

В любом случае, компонент тут вообще не при делах - устанавливает MODX.

**Comment by akimsullec** [comment]
Ок, я думал что пакет установки как-то может быть с этим связан и перенастроен :)
Если это на уровне MODX, то вопросов нет, буду просто иметь это в виду.

Бэкап есть :)

**Comment by bezumkin** [comment]
Насколько я понимаю, если пакета нет в системе - то MODX просто не парится про директорию и затирает ее.
А если пакет уже есть - то пишет внутрь и старые файлы остаются.

Искать это в коде желания нет, но по всей логике выходит только так.

**Comment by akimsullec** [comment]
Это-то и странно при заявленной мультисайтовости :)
Попробую с ними пообщаться по этому вопросу.

**Comment by bezumkin** [comment]
Да нет, не странно.
Насколько я знаю, такой системы классов больше нигде нет, только в MS2, mSearch2 и Office.

То есть, такого вопроса раньше и не могло появиться.

Ну и обычно люди используют контексты - там тоже проблем не будет.
