### ISSUE TITLE
Добавить поле типа <select> для фильтров

### ISSUE THREAD

**Issue by alexeyrus** [Ibochkarev/miniShop2#81]
Полезная была бы функция для оформления фильтров
 <select>
    <option>Tag 1</option>
    <option>Tag 2</option>
    <option>Tag 3</option>
  </select>

**Comment by bezumkin** [comment]
Еще бы понять, о чем речь?

**Comment by alexeyrus** [comment]
добавить новый чанк для фильтров
tpl.mFilter2.filter.select
< select >
  < option >Tag 1</ option >
  < option >Tag 2</ option >
  < option >Tag 3</ option >
</ select >
и добавить логику для работы в js

**Comment by bezumkin** [comment]
Это репозиторий miniShop2

А mSearch2 и так отлично работает работает с параметрами товаров + можно указывать свои чанки каждому фильтру.

Нет только логики работы с селектами, но это можно добавить самостоятельно.
