### ISSUE TITLE
Вывод товаров при использовании двух контекстов

### ISSUE THREAD

**Issue by MazheM** [Ibochkarev/miniShop2#87]
При создании двух контекстов(например web и en, для двуязычного сайта) товары minishop начинают выводится во всех категориях, независимо от контекста и категории.
Два языка на сайте делал как предлагалось Василием.
Пример: http://s3953.modx-test.com и другая категория http://s3953.modx-test.com/cat4/ (Знаю что скоро исчезнет, но надеюсь удивить проблему успеете)
Так же прикладываю картинку, где показано что товар отображается во всех катего

**Comment by bezumkin** [comment]
В сниппете msProducts можно указать и контекст и категорию.

Если что-то не так, можно включить лог и посмотреть, почему выбираются именно эти товары.

**Comment by MazheM** [comment]
В моем случае я проблему решил: [[!getPage? &element=`msProducts` &parents=`[[*id]]` ]]
Но думаю это не самое изящное решение и можно учесть это еще в сниппите, но боюсь что не знаю как.
