### ISSUE TITLE
miniShop2  2.1.2 - нет генерации превью картинок из amazon S3 при загрузке

### ISSUE THREAD

**Issue by me6iaton** [Ibochkarev/miniShop2#88]
при загрузке картинок в источник файлов amazon S3, не происходит генерация превью картинки. 
В логах появляется:
[2013-11-05 02:35:44](WARN @ /var/www/shantambala/www/core/components/minishop2/model/minishop2/msproductfile.class.php : 41) PHP notice: Array to string conversion
[2013-11-05 02:35:44](ERROR @ /assets/components/minishop2/connector.php) Could not generate thumbnails for image with id = 143. Could not retrieve file "67/Array" from media source. file_folder_err_ae: /67/
Если кликнуть по картинке и выбрать обновить превьюшки - превью создается 

update:
проблема здесь:
https://github.com/bezumkin/miniShop2/blob/ffe295dbf199f9920ccd7de9a7ef10d1ae8f4ea8/core/components/minishop2/model/minishop2/msproductfile.class.php#L40
в $mediaSource -> errors есть запись:  file_folder_err_ae: /67/  т. е   "Каталог с таким именем уже существует"

если удалить проверку то превью создаются нормально, но наверно это не очень хорошо )
<code>
if (!empty($this->mediaSource->errors['file'])) {
   return 'Could not retrieve file "'.$this->path.$this->file.'" from media source. '.$this->mediaSource->errors['file'];
}
</code>

**Comment by bezumkin** [comment]
Не могу повторить.

Подключил Amazon S3, создал юзера IAM, загрузил картинку - всё нормально.
<a rel="fancybox" href="http://st.bezumkin.ru/files/f/2/d/f2d52882bfeca156fb1669c835510aa8.png"><img src="http://st.bezumkin.ru/files/f/2/d/f2d52882bfeca156fb1669c835510aa8s.jpg" class="fancybox thumbnail center"></a>
