### ISSUE TITLE
Foreign characters are stripped from checkout form

### ISSUE THREAD

**Issue by lottaar** [Ibochkarev/miniShop2#89]
When entering a foreign character in the checkout form, such as the Swedish characters åäö, these are stripped out from the form. Any consecutive characters in the input field also vanish. Since these characters are very common in the Swedish language it makes the store unusable.

**Comment by bezumkin** [comment]
Just <a href="http://translate.google.com/translate?hl=ru&sl=ru&tl=en&u=http%3A%2F%2Fbezumkin.ru%2Fmodx%2Fminishop2%2Fclasses%2F1126%2F">override validation method</a>

**Comment by lottaar** [comment]
Am I supposed to change the System Setting ms2_order_handler_class from msOrderHandler to myOrderHandler? When I do that the site goes blank...

**Comment by lottaar** [comment]
Right, sorry, I think it's working now. Google Translate had added some mumbo jumbo in the source, that's why it didn't play nice at first. This is what I put in myOrderHandler to allow åäö, I hope it's correct:

<?php
 class myOrderHandler extends msOrderHandler {

```
 public function validate($key, $value) {
     switch ($key) {
         case 'receiver':
             $tmp = preg_replace(array('/[^-a-zåäö\s\.]/iu', '/\s+/', '/\-+/', '/\.+/'), array('', ' ', '-', '.'), $value);
         break;
         case 'street':
             $tmp = preg_replace(array('/[^-a-zåäö\s\.]/iu', '/\s+/', '/\-+/', '/\.+/'), array('', ' ', '-', '.'), $value);
         break;
         case 'building':
             $tmp = preg_replace(array('/[^-a-zåäö\s\.]/iu', '/\s+/', '/\-+/', '/\.+/'), array('', ' ', '-', '.'), $value);
         break;
         case 'city':
             $tmp = preg_replace(array('/[^-a-zåäö\s\.]/iu', '/\s+/', '/\-+/', '/\.+/'), array('', ' ', '-', '.'), $value);
         break;

         default:
             return parent::validate($key, $value);
     }

     if ($value === false) {$value = '';}
     return $value;
 }
```

 }

Thank you so much your help!

**Comment by bezumkin** [comment]
You are welcome!
