### ISSUE TITLE
При включенном сжатии js и css в админке не показываются иконки

### ISSUE THREAD

**Issue by alroniks** [Ibochkarev/miniShop2#90]
../../img/mgr/glyphicons-halflings.png - этот файл
Проблема из-за относительного пути. Так как все сжимается в один файл и он располагается в /manager/min/, то путь считается оттуда и картинка со спрайтами не находится.

**Comment by bezumkin** [comment]
<a href="https://github.com/bezumkin/miniShop2/issues/1">С добрым утром!</a>

Абсолютный url не могу прописать, так как у assets может быть другое имя.

**Comment by alroniks** [comment]
Щас покажу PR
