### ISSUE TITLE
Добавить возможность создания копий товаров

### ISSUE THREAD

**Issue by alroniks** [Ibochkarev/miniShop2#92]
Аналогично, как копируются ресурсы. Полезно, когда есть товар с весом 100 грамм, а нужно добавить такой же с весом по 200 и 500 грамм и разной стоимостью и возможно скидками и другими параметрами. Да и в целом копия уже созданного товара - удобная штука.

**Comment by bezumkin** [comment]
Есть и в контекстном меню, и в панеле редактирования товара.

Не помню, когда появилось, но эту задачу можно закрыть.
