### ISSUE TITLE
Product Gallery not showing correct Images

### ISSUE THREAD

**Issue by RossUK88** [Ibochkarev/miniShop2#97]
After adding an Image to the gallery the thumbnail is the minishop standard image.

Here are some screens to show what the problem is:

Editing a product:
http://gyazo.com/b72cc85bf2f451505fb5b3a008c5b369

Display on live website:
http://gyazo.com/ef074a789489d8e5d6a7696803845fc9

I've cleared cache's, flushed sessions. reuploaded, renammed, tried different files even ones that have worked on another site that i use minishop on and nothing seems to be working.

**Comment by RossUK88** [comment]
As an update, I think I have located the problem:

In the msGallery snippet:

<pre>
else {
        if (empty($outputSeparator)) {$outputSeparator = "\n";}
        $output = implode($outputSeparator, $output);
        if (!empty($tplOuter) && !empty($output)) {
echo "pre";
print_r($images);
echo "/pre";
            $arr = array_shift($images);
            $arr['rows'] = $output;
echo "pre";
var_dump($output);
echo "/pre";
            $output = $pdoFetch->getChunk($tplOuter, $arr);
        }
        elseif (empty($output)) {
            $output = !empty($tplEmpty)
                ? $pdoFetch->getChunk($tplEmpty)
                : '';
        }
</pre>

it seems as though the $output variable is technically empty; the var_dump brings this
string(298) "

"

Any ideas on why this is happening?

**Comment by bezumkin** [comment]
Some bug on your hosting, I don`t know.

Try to check this here - http://modx-test.com
